services:
    mongodb:
        image: mongo:7
        container_name: mongodb
        # ports:
        #   - "27017:27017"
        volumes:
            - mongo_data:/data/db
        restart: unless-stopped

    postgres:
        image: postgres:17
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        # ports:
        #   - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql
        restart: unless-stopped

    neo4j:
        image: neo4j:5.25-community
        container_name: neo4j
        environment:
            - NEO4J_server_memory_heap_initial__size=256m
            - NEO4J_server_memory_heap_max__size=256m
            - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
        volumes:
            - neo4j_data:/data
            - neo4j_logs:/logs
        restart: unless-stopped

    backend:
        build: ./backend
        container_name: backend
        ports:
            - "3000:3000"
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb
            - postgres
            - neo4j
        restart: unless-stopped

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/live/sivaranjani.me/fullchain.pem:/etc/ssl/certs/fullchain.pem
            - /etc/letsencrypt/live/sivaranjani.me/privkey.pem:/etc/ssl/private/privkey.pem
        depends_on:
            - backend
        restart: unless-stopped

volumes:
    mongo_data:
    pg_data:
    neo4j_data:
    neo4j_logs:
